# Generated by Django 3.1 on 2025-01-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_user_is_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='req_agent',
            field=models.BooleanField(default=False),
        ),
    ]
